### ISSUE TITLE
A second chance to the push gateway

### ISSUE THREAD

**Issue by githubdeb** [immanuelfodor/rocketchat-push-gateway#5] opened 2022-09-11 00:06 UTC

**Comment by immanuelfodor** [comment] 2022-09-13 10:36
Hi @githubdeb, 

> However, I would need a way to read from RC the user who send and the one who receive ids and very-long-token and the payload.
> I saw all this information in the RC logs, but I don't know where I can read it with code.

In this case, you'd need to modify the codebase of RC or develop a custom "plugin" to read it since this information only exists in RC internally, so you'd need to hook into this internal event. That is why they make it available as a "webhook" with the possibility to receive the event as a HTTP POST message through a push gateway. I think it's a lot easier to use the gateway than to modify and constantly rebase RC's codebase. 

> In this situation I don't think I need apprise.

Theoretically, it's correct, you could just curl the Gotify server but see the previous explanation. With this gateway, apprise makes the curling a lot easier through their Gotify notification channel which hides the implementation details and we just need to pass a couple of parameters to make the call. 

> I'm trying to make it work without docker.

Of course, it's possible, Docker just makes the packaging and setting up the environment easier and reproducible. Should you have Python installed in a VM or LXC container or some bare metal machine, install the requirements with pip, start the gateway as a service at boot, and you're good to go. 

> Clearly it does not find something.

Yes. To debug this, you need to be aware on which hosts the my.domain.com is resolvable to where through DNS and what is considered as localhost from which perspective (client side, server side). You need to be able to curl the gateway from the server running RC (if it's a container, then from within the container), and you need to be able to curl Gotify from the server running the gateway. Furthermore, all the payloads and configs need to be the same and correct that would each service expect, so for example, what you added to the push gateway's apprise config, you need to use those parameters when curling from there to be sure that everything works. I think your problem resolves somewhere here. Try to visualize on a network diagram where your services are installed, where working or not working communication happens, etc, it might help, just as rubber duck debugging.

**Comment by githubdeb** [comment] 2022-09-18 00:01
Ok.
1. I can curl the gateway from the server running RC. In fact both are on the same machine. It works when I curl to http://localhost:5000 from command prompt. 
2. It also works when I curl from command prompt to Gotify server.
My general schema looks like this
RC Server ------> push settings (http://localhost:5000) ------->apprise file -------> Gotify server.

1 and 2 means everything from push settings(http://localhost:5000) -----> apprise file ------>Gotify server works.
The only part not working is the one from RC to the push gateway. I don't get push notifications to Gotify from RC.
Any ideas?

**Comment by immanuelfodor** [comment] 2022-09-26 14:32
And no Docker is involved anywhere in the process? All the servers (RC, push gateway, Gotify) run with native install on the same machine exposed by their default ports?

**Comment by githubdeb** [comment] 2022-09-27 13:13
Correct. No Docker is involved anywhere. All the servers (RC, push gateway, Gotify) run with native install on the same machine using their default ports.

**Comment by immanuelfodor** [comment] 2022-09-29 12:25
Well, that is most interesting, `localhost` should mean the same machine in all contexts. 

One thing I can think of is that RC is in fact not sending any push notifications out. There are cases when RC thinks that the recipient has already seen the message, so it doesn't send a push out. Try being in a channel with 2 users, and avoid using the 2nd user's account on the web in another browser (tab) or on mobile (it should have a mobile device login, of course), then send a message in that channel with the 1st user. In this case, a push should be definitely triggered for the 2nd user as they can't see the message on any of their devices (web or mobile). 

One other thing to try is to use an online request bin to examine the push contents. A problem may be that the link should contain RC's expected path but this one for example can handle an arbitrary path behind the UUID in the URL: https://webhook.site/ so add the URL with UUID as push gateway in RC's settings (e.g. https://webhook.site/xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx/ , and see what happens with the first method, is there any push at all, and if yes, what the content is.

Third idea is to change `localhost` to its IP equivalent `127.0.0.1`, so http://127.0.0.1:5000/ . Maybe `npm` resolves it to something else, I don't know.

**Comment by githubdeb** [comment] 2022-10-01 21:25
Have a look at the logs
I20221001-21:01:03.795(0) Integrations ➔ Outgoing WebHook.debug Starting search for triggers for the room: X7dQEysydWBJJtkpwtHWrrbEakjvrie8g8 
I20221001-21:01:03.798(0) Integrations ➔ Outgoing WebHook.debug Found 0 to iterate over and see if the match the event. 
I20221001-21:01:05.639(0) Push ➔ debug Sending notification {   createdAt: 2022-10-01T21:01:05.623Z,   createdBy: '<SERVER>',   sent: false,   sending: 0,   from: 'push',   title: 'tanta',   text: 'Hi there',   userId: 'tHWrrbEakjvrie8g8',   payload: {     host: 'https://chat.mystockphotos.eu/',     messageId: '0Kv3Tln5u4KY8sfLK',     notificationType: 'message',     rid: 'X7dQEysydWBJJtkpwtHWrrbEakjvrie8g8',     sender: { _id: 'X7dQEysydWBJJtkpw', username: 'tanta', name: 'tanta' },     senderName: 'tanta',     type: 'd'   },   badge: 1,   sound: 'default',   notId: -1398311196,   apn: { category: 'MESSAGE' },   gcm: {     image: 'https://chat.mystockphotos.eu/images/logo/android-chrome-192x192.png',     style: 'inbox'   } } 
I20221001-21:01:05.641(0) Push ➔ debug send message "tanta" to userId tHWrrbEakjvrie8g8 
I20221001-21:01:05.648(0) Push ➔ debug send to token {   gcm: 'cAmmTtMCQ9-Fv-q5ye6uDQ:APA91bGpCgX1t6pzMTHIVvgwj4AEPab8SrulfXE8DZbqdsGr5w6nh6UJv3I7IbSSibKuE1gLDc7xpnaom2ek8sR4EpmyZXCLpAVUD2cWcKEZtR5SficMcs8l0Q8b62kON6qxswbnG64Y' } I20221001-21:01:05.650(0) Push ➔ debug send to token {   gcm: 'cAmmTtMCQ9-Fv-q5ye6uDQ:APA91bGpCgX1t6pzMTHIVvgwj4AEPab8SrulfXE8DZbqdsGr5w6nh6UJv3I7IbSSibKuE1gLDc7xpnaom2ek8sR4EpmyZXCLpAVUD2cWcKEZtR5SficMcs8l0Q8b62kON6qxswbnG64Y' } I20221001-21:01:05.651(0) Push ➔ debug Sent message "tanta" to 0 ios apps 1 android apps 
I20221001-21:01:05.664(0) Push ➔ debug GUIDE: The "appTokensCollection" - No APN clients have registered on the server yet... 
I20221001-21:01:05.714(0) API ➔ debug POST: /api/v1/subscriptions.read 
I20221001-21:01:05.718(0) Meteor ➔ method readMessages -> userId: X7dQEysydWBJJtkpw, arguments: ["X7dQEysydWBJJtkpwtHWrrbEakjvrie8g8"] 
I20221001-21:01:05.725(0) API ➔ debug Success { statusCode: 200, body: { success: true } } 
I20221001-21:02:00.760(0) SyncedCron ➔ info Starting "Generate download files for user data". 
I20221001-21:02:00.766(0) SyncedCron ➔ info Finished "Generate download files for user data". 
I20221001-21:04:00.787(0) SyncedCron ➔ info Starting "Generate download files for user data". 
I20221001-21:04:00.798(0) SyncedCron ➔ info Finished "Generate download files for user data".

**Comment by githubdeb** [comment] 2022-10-01 21:29
Take a look below:
I20221001-21:01:03.795(0) Integrations ➔ Outgoing WebHook.debug Starting search for triggers for the room: X7dQEysydWBJJtkpwtHWrrbEakjvrie8g8 
I20221001-21:01:03.798(0) Integrations ➔ Outgoing WebHook.debug Found 0 to iterate over and see if the match the event. 
I20221001-21:01:05.639(0) Push ➔ debug Sending notification {   createdAt: 2022-10-01T21:01:05.623Z,   createdBy: '<SERVER>',   sent: false,   sending: 0,   from: 'push',   title: 'tanta',   text: 'Hi there',   userId: 'tHWrrbEakjvrie8g8',   payload: {     host: 'https://chat.mystockphotos.eu/',     messageId: '0Kv3Tln5u4KY8sfLK',     notificationType: 'message',     rid: 'X7dQEysydWBJJtkpwtHWrrbEakjvrie8g8',     sender: { _id: 'X7dQEysydWBJJtkpw', username: 'tanta', name: 'tanta' },     senderName: 'tanta',     type: 'd'   },   badge: 1,   sound: 'default',   notId: -1398311196,   apn: { category: 'MESSAGE' },   gcm: {     image: 'https://chat.mystockphotos.eu/images/logo/android-chrome-192x192.png',     style: 'inbox'   } } 
I20221001-21:01:05.641(0) Push ➔ debug send message "tanta" to userId tHWrrbEakjvrie8g8 
I20221001-21:01:05.648(0) Push ➔ debug send to token {   gcm: 'cAmmTtMCQ9-Fv-q5ye6uDQ:APA91bGpCgX1t6pzMTHIVvgwj4AEPab8SrulfXE8DZbqdsGr5w6nh6UJv3I7IbSSibKuE1gLDc7xpnaom2ek8sR4EpmyZXCLpAVUD2cWcKEZtR5SficMcs8l0Q8b62kON6qxswbnG64Y' } I20221001-21:01:05.650(0) Push ➔ debug send to token {   gcm: 'cAmmTtMCQ9-Fv-q5ye6uDQ:APA91bGpCgX1t6pzMTHIVvgwj4AEPab8SrulfXE8DZbqdsGr5w6nh6UJv3I7IbSSibKuE1gLDc7xpnaom2ek8sR4EpmyZXCLpAVUD2cWcKEZtR5SficMcs8l0Q8b62kON6qxswbnG64Y' } I20221001-21:01:05.651(0) Push ➔ debug Sent message "tanta" to 0 ios apps 1 android apps 
I20221001-21:01:05.664(0) Push ➔ debug GUIDE: The "appTokensCollection" - No APN clients have registered on the server yet... 
I20221001-21:01:05.714(0) API ➔ debug POST: /api/v1/subscriptions.read 
I20221001-21:01:05.718(0) Meteor ➔ method readMessages -> userId: X7dQEysydWBJJtkpw, arguments: ["X7dQEysydWBJJtkpwtHWrrbEakjvrie8g8"] 
I20221001-21:01:05.725(0) API ➔ debug Success { statusCode: 200, body: { success: true } } 
I20221001-21:02:00.760(0) SyncedCron ➔ info Starting "Generate download files for user data". 
I20221001-21:02:00.766(0) SyncedCron ➔ info Finished "Generate download files for user data". 
I20221001-21:04:00.787(0) SyncedCron ➔ info Starting "Generate download files for user data". 
I20221001-21:04:00.798(0) SyncedCron ➔ info Finished "Generate download files for user data".

**Comment by immanuelfodor** [comment] 2022-12-16 11:24
I close this issue for now as I don't see any problem with the gateway itself, this must be an issue with the hosting environment. We can continue the debug on the closed issue anyways.

**Closed as completed by immanuelfodor** 2022-12-16 11:24 UTC
